
export const Types = {
  LOGIN: 'LOGIN',
  LOGOUT : 'LOGOUT',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  
  GET_PROFILE:'GET_PROFILE',
  UPDATE_PROFILE:'UPDATE_PROFILE',
  UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
  
  FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS',
  UPDATE_CART: 'UPDATE_CART',
  UPDATE_SEARCH :'UPDATE_SEARCH',
}