
export const Types = {
  LOGIN: 'LOGIN',
  LOGOUT : 'LOGOUT',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
  FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS',
  UPDATE_CART: 'UPDATE_CART'
}